language: objective-c
osx_image: xcode9.2
rvm:
- 2.2
env:
  global:
  - secure: hNgSuWPIaBhZP3D2+Cs05YxgbAznb2JnH4s7cZGbHKaXQHCEAWS6PTDLaIZZv1jiMD5QirfDlsFD6nDf48R9xzTICJ8yPUWr4ScFddjX+Y8LXA9pP7e3xUElYiBXF217O0gQVSV869G8TsPFWoVhQDuBrotI37MOs8I7+8Ga6HXJuIVQ7ZY+4hLFYb037mtaNtSbIZK6UMGNQ0LbhSHdJb58M6X09k6O6PotRHm6C+lmyyx7anFqURUNkqLjSD3rQgqvs6eHNEvIMRL/VIZICr2savaB0mzfQHSvz8qGGepiTLN1PAgJy6PN/TTkBFS7t9I+5bx4muagHIdTqJtF8uAcl1/KPO+RFss90BelES1qRyAPR3mWdKXe7i/EvIAD96vClGSPvpytyxx6sCE5QcsF/sSyp28lDyihIJY25Hu7iKjoDr+UxB4ctn/bfAdHTPwJhXoE0PXADb41Zlv7xntWJXn9YVjw1zJFWSPum0QT/gyt7jZP4PWGO0TrQK5uNd35kc8EDaO9L04fx/JKq71bmmxMbwjLhSehbab2g7VacPqs9xx7UgsmgBTp7WkMwHYEjda34pPoB3meJF+Qj4ND98jpWq4OJIOdJmbsI+fem6BGYy15Z9CSuejKNS5J5J9Ga+4Z+8540MAwgKYlz9J8wDK3B9ICe9B0MatXVfA=
  - secure: vAVNll7+OkYmHf6GztkGNKNR3xgzoIqpDjyvNxeTqaZlzxrPaJg0y2mpYmK/fFV2Fi2rQv2YdvntclXVdunJnTeAudrJsyKLDUOk3Gh7586meh4zy63eL+hS4oZGU8viLMgaxzrUceJyeTcWfF4ivmdh7BHGh8aKgnsJKIIgFCRAOgaFx4c/5585a871LyQWIAN8dHkdG1BP6Zk6tX5tW9rJVGNAZLpkhO+O9W3rTaQgMIrY4m0JLcpt/p+ho+6msf/AZ5q8AQ0QCyd2j1BUi2K8Y3htfuNvCGFgJL/59uv6DMVMXc1xKdFeqUMIuxAzlNGz6ugZl6udx2t7rRkxEdIOso/MmHE8tiGUHTOOJTGckR9CNXDDnsbympodSWx5Xn55xIEi7CgFFSW40d3O4jZc35y/Coi3p+8UUBrDn92dmTJs8HV2q46CE1EtAeSh5HjhWXV6fu6XCd9eW1mo1U0KpDf++cTmVlpE+9/3We8agyQ7xG5vADT+N6ybfMbj5E6e+9kAzjFYz3GHO7hXN6KnMXM5Y3xLGi6M9rsEGWAdr2Cf8ld8f34blnOWvnyxxI3BOzi9aXMtLSXLwY9xzU3COXCIo+2eRCYdFSPzLvgCqxX0SarTKVCVaeJck8aFP/puGn1QeMFkV6t2SDJiWpfasfsjJL45GykIR4CWZ6o=
  - secure: Uf156vX60e+F39Xfr6QrEgt4VtTLXHaRXs9hELFETITBPoaBc19M8Cy0l9k2X02GU/eRr2pSAyWr6jeEnDcN1IJFoKc4eDEwptY6Ms1sYeXLlePZdWmgt7j3ncj4ALkeI9LuxluGUuTqGGz8rhEBeV3Xf+EclSTcKdAimKW82yk8hCarrjGDvZJ9BnNIrk7AJ2lhahMH5J3P7qinLQg02Me0JNPO0hALCKNFLi7SfzgLoV+zo2EJyHSglAXe8lJxnrnQMpuysFwDx+AiCfbxRwIqtwpl1Iwv9pEY3Hw0yDZwjOOUQI7Q6mrKGylslf5Lt9gZcJkxh7fLeXLWqGh/F0+8+S5Vr5jnxuUz2HC8RRQQSmsP2sVo605t6phBNIw+GFrgq4DT+yzOJf6NA4zatFTbqIkZoxmujmNB8PGx4YJvIeCbzFhpQr2nXdPH2kKVxyfA8bXQ1zlFRyYf0EEj8k//O+rIMkC+a6vsCOpMNtLSH6cyFFkA7ZaIj6QY2xIA/TG+P5ErKZmrpVxtsaQ4GwIXzGYTh48D8V87QxPKRKy2/LN91Fntc+huTK9qRlaPMHdM4Z/9Rzh+wlF/vHq713f9ssgGqBwN+LEFwE3iUM2NYt8SokhPjvWAZCeRrgm0xOlVW2QImIFLKldlW+wYJ79OR/2SPBpnXLeitIHO414=
cache:
  directories:
  - "$UNITY_DOWNLOAD_CACHE"
before_install:
- chmod a+x ./travis-build/*.sh
install:
- cat /etc/hosts
- "./travis-build/install-unity.sh"
script:
- "./travis-build/build.sh"
- "./travis-build/run-tests.sh"
- "./travis-build/clean-up.sh"
